### ISSUE TITLE
为啥发了/p b19后显示不出成绩

### ISSUE THREAD

**Issue by KasumiYuku** [Walkersifolia/PhigrosLibrary-plugin#1]
rks和成绩都没显示出来qwq
![image](https://github.com/Walkersifolia/PhigrosLibrary-Plugin/assets/107661829/4406361b-ca00-4b75-8e5d-e3457e662b9c)

**Comment by KasumiYuku** [comment]
stk绑定了

**Comment by Walkersifolia** [comment]
> stk绑定了

注意事项里的栏目看了吗，以及截图给我看看控制台报错

**Comment by Afkeru** [comment]
> > stk绑定了
> 
> 注意事项里的栏目看了吗，以及截图给我看看控制台报错

好像没有没有报错（但佬回复好快）
![image](https://github.com/Walkersifolia/PhigrosLibrary-Plugin/assets/107661829/26e95324-8c73-4332-a443-53440142a3f6)

**Comment by KasumiYuku** [comment]
> > stk绑定了
> 
> 注意事项里的栏目看了吗，以及截图给我看看控制台报错

看了，终端好像没有没有报错（但佬回复好快）
![image](https://github.com/Walkersifolia/PhigrosLibrary-Plugin/assets/107661829/61f66c98-35dd-4d46-b988-57fea08758e3)

**Comment by KasumiYuku** [comment]
> > > stk绑定了
> > 
> > 
> > 注意事项里的栏目看了吗，以及截图给我看看控制台报错
> 
> 看了，终端好像没有没有报错（但佬回复好快） ![image](https://user-images.githubusercontent.com/107661829/243051562-61f66c98-35dd-4d46-b988-57fea08758e3.png)

处理完之后就发了只带了UI没带成绩的成绩图

**Comment by Walkersifolia** [comment]
> > > > stk绑定了
> > > 
> > > 
> > > 注意事项里的栏目看了吗，以及截图给我看看控制台报错
> > 
> > 
> > 看了，终端好像没有没有报错（但佬回复好快） ![image](https://user-images.githubusercontent.com/107661829/243051562-61f66c98-35dd-4d46-b988-57fea08758e3.png)
> 
> 处理完之后就发了只带了UI没带成绩的成绩图

p-start.bat启动了吗，应该是新开了个窗口，以及服务端也正常启动了吗，这俩正常情况下都会新开窗口

**Comment by Walkersifolia** [comment]
> > > > stk绑定了
> > > 
> > > 
> > > 注意事项里的栏目看了吗，以及截图给我看看控制台报错
> > 
> > 
> > 看了，终端好像没有没有报错（但佬回复好快） ![image](https://user-images.githubusercontent.com/107661829/243051562-61f66c98-35dd-4d46-b988-57fea08758e3.png)
> 
> 处理完之后就发了只带了UI没带成绩的成绩图

我去尝试一下复现错误（回复快是因为刚好在写readme，写完保存就看到一个issue）

**Comment by KasumiYuku** [comment]
@Walkersifolia 
![image](https://github.com/Walkersifolia/PhigrosLibrary-Plugin/assets/107661829/069066ed-b72a-46b4-b1a7-b725f25186a4)
![image](https://github.com/Walkersifolia/PhigrosLibrary-Plugin/assets/107661829/df747b55-699b-42cd-b9ba-d4998ca545f9)

好吧新开的两个窗口报了错（）

**Comment by Walkersifolia** [comment]
> > > > stk绑定了
> > > 
> > > 
> > > 注意事项里的栏目看了吗，以及截图给我看看控制台报错
> > 
> > 
> > 看了，终端好像没有没有报错（但佬回复好快） ![image](https://user-images.githubusercontent.com/107661829/243051562-61f66c98-35dd-4d46-b988-57fea08758e3.png)
> 
> 处理完之后就发了只带了UI没带成绩的成绩图

我刚刚去尝试复现了错误，把服务端关掉之后出现了一样的情况，你应该是PhigrosLibrary服务端没有正常启动，那个需要手动启动的

**Comment by Walkersifolia** [comment]
> @Walkersifolia ![image](https://user-images.githubusercontent.com/107661829/243051697-069066ed-b72a-46b4-b1a7-b725f25186a4.png) ![image](https://user-images.githubusercontent.com/107661829/243051713-df747b55-699b-42cd-b9ba-d4998ca545f9.png)
> 
> 好吧新开的两个窗口报了错（） 上面说save，update和channelRead方法中发生了错误

这个啊，这个是账号存档问题，账号上有多个存档导致冲突了，目前来说，会等服务端下次版本更新解决这个限制，你的插件已经正常跑起来了

**Comment by KasumiYuku** [comment]
> > @Walkersifolia ![image](https://user-images.githubusercontent.com/107661829/243051697-069066ed-b72a-46b4-b1a7-b725f25186a4.png) ![image](https://user-images.githubusercontent.com/107661829/243051713-df747b55-699b-42cd-b9ba-d4998ca545f9.png)
> > 好吧新开的两个窗口报了错（） 上面说save，update和channelRead方法中发生了错误
> 
> 这个啊，这个是账号存档问题，账号上有多个存档导致冲突了，目前来说，会等服务端下次版本更新解决这个限制，你的插件已经正常跑起来了

噢噢，我知道了，谢谢佬😘

**Comment by Walkersifolia** [comment]
9号更新，在之后记得去PhigrosLibrary服务端的仓库看看，有问题记得发新的issue

**Comment by KasumiYuku** [comment]
> 9号更新，在之后记得去PhigrosLibrary服务端的仓库看看，有问题记得发新的issue

好的ww
