### ISSUE TITLE
一个小小的idea

### ISSUE THREAD

**Issue by KasumiYuku** [Walkersifolia/PhigrosLibrary-plugin#2]
佬可以考虑加一个根据b19那个模糊的曲绘猜歌名或者猜曲师的娱乐功能（）
如果名很复杂很长可以加ABC三个选项选，猜对了奖励（比如鼓励之类的话）猜错了给惩罚（比如禁言什么的）
猜完后再把取名，曲师以及完整的曲绘发出来

**Comment by KasumiYuku** [comment]
看佬对项目的定位也有娱乐，就小小提议一下（）

**Comment by QiXingQXX** [comment]
> 

加个彩蛋写一下后边曲绘的名字？

**Comment by QiXingQXX** [comment]
> 佬可以考虑加一个根据b19那个模糊的曲绘猜歌名或者猜曲师的娱乐功能（） 如果名很复杂很长可以加ABC三个选项选，猜对了奖励（比如鼓励之类的话）猜错了给惩罚（比如禁言什么的） 猜完后再把取名，曲师以及完整的曲绘发出来

加个彩蛋写一下后边曲绘的名字？至于惩罚什么的群里内定可以，或者出那种回复图片可以获取曲绘名字的功能，看更倾向哪个了
