### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by S-t-e-v-e-e** [Walkersifolia/PhigrosLibrary-plugin#4]
![报错如下](https://github.com/Walkersifolia/PhigrosLibrary-Plugin/assets/117198625/8b78882d-cf6a-4bb6-9f75-c783b68b1796)

**Comment by Walkersifolia** [comment]
我是傻逼（readme写错了），这个问题很好解决，你去plugins文件夹，把本插件的后面的Plugin改成plugin就行，就是把`PhigrosLibrary-Plugin`改成`PhigrosLibrary-plugin`

**Comment by S-t-e-v-e-e** [comment]
草

**Comment by S-t-e-v-e-e** [comment]
![image](https://github.com/Walkersifolia/PhigrosLibrary-Plugin/assets/117198625/697c1690-937a-4b80-9ea6-09af243902f3)
我 b o t 呢
