### ISSUE TITLE
佬，你帮助是不是打错字了

### ISSUE THREAD

**Issue by S-t-e-v-e-e** [Walkersifolia/PhigrosLibrary-plugin#5]
![image](https://github.com/Walkersifolia/PhigrosLibrary-Plugin/assets/117198625/eac6ed10-a53d-4f47-b92f-75051cea14a2)
![image](https://github.com/Walkersifolia/PhigrosLibrary-Plugin/assets/117198625/74061396-9862-45b8-a3f0-6ef7fc2f4638)

**Comment by S-t-e-v-e-e** [comment]
getsk和getstk

**Comment by Walkersifolia** [comment]
喔喔，确实打错了，实际上是getstk（我是笨蛋

**Comment by S-t-e-v-e-e** [comment]
草

**Comment by S-t-e-v-e-e** [comment]
都打错了是吧

**Comment by Walkersifolia** [comment]
> 都打错了是吧

不不，输入getstk能触发，帮助写错了（待会改，github的readme没写错

**Comment by S-t-e-v-e-e** [comment]
![image](https://github.com/Walkersifolia/PhigrosLibrary-Plugin/assets/117198625/bcc2cea8-c7fc-4e01-8545-9fc5ac2ec7f6)
好像没响应（

**Comment by Walkersifolia** [comment]
> ![image](https://user-images.githubusercontent.com/117198625/244748289-bcc2cea8-c7fc-4e01-8545-9fc5ac2ec7f6.png) 好像没响应（

是/p getstk

**Comment by S-t-e-v-e-e** [comment]
草

**Comment by 112121212167987534524** [comment]
##我是傻逼

**Comment by 112121212167987534524** [comment]
**### 我是傻逼**

**Comment by S-t-e-v-e-e** [comment]
### 我是傻逼
