### ISSUE TITLE
这是什么报错

### ISSUE THREAD

**Issue by S-t-e-v-e-e** [Walkersifolia/PhigrosLibrary-plugin#6]
![image](https://github.com/Walkersifolia/PhigrosLibrary-Plugin/assets/117198625/e767d0c2-c870-4b69-9a7d-979a7b63fc21)
如图

**Comment by Walkersifolia** [comment]
没有安装puppeteer，在yunzai根目录执行npm install puppeteer，但是不对啊，好多插件都要用到puppeteer

**Comment by S-t-e-v-e-e** [comment]
![image](https://github.com/Walkersifolia/PhigrosLibrary-Plugin/assets/117198625/f791c3f5-0a6f-43f8-8744-8bed5f1fc75f)
是这个吗

**Comment by Walkersifolia** [comment]
对

**Comment by S-t-e-v-e-e** [comment]
但是只有这个插件出错了

**Comment by Walkersifolia** [comment]
哦，你这个是喵崽啊，我没用过，检查bot根目录下，`./lib/puppeteer/puppeteer.js`是否存在，我是用绝对路径import的，然后看看其他插件的puppeteer的import是在哪个目录
![image](https://github.com/Walkersifolia/PhigrosLibrary-Plugin/assets/129571444/0575f7c5-edeb-434d-84d2-75824fea5927)

**Comment by S-t-e-v-e-e** [comment]
![image](https://github.com/Walkersifolia/PhigrosLibrary-Plugin/assets/117198625/08891da9-6afa-4614-82cf-bc86f53c45a6)

**Comment by Walkersifolia** [comment]
> ![image](https://user-images.githubusercontent.com/117198625/244853548-08891da9-6afa-4614-82cf-bc86f53c45a6.png)

那不对呀，不应该有问题呀

**Comment by S-t-e-v-e-e** [comment]
![image](https://github.com/Walkersifolia/PhigrosLibrary-Plugin/assets/117198625/d1d28c62-960f-4b87-9b92-50885ed33223)
🤔

**Comment by S-t-e-v-e-e** [comment]
某插件的

**Comment by Walkersifolia** [comment]
> 

node模块的puppeteer和lib里面的代码写法不太一样，我有空搭一个喵崽看一下吧，云崽插件无法完全兼容喵崽是很正常的

**Comment by S-t-e-v-e-e** [comment]
![image](https://github.com/Walkersifolia/PhigrosLibrary-Plugin/assets/117198625/364b005d-92d3-46c2-81ad-47d1852162f4)
貌似不太支持直接调用puppteer.js了

**Comment by Walkersifolia** [comment]
离谱，我总不能为了喵崽兼容内置puppeteer，那样冗杂程度就太离谱了

**Comment by S-t-e-v-e-e** [comment]
![image](https://github.com/Walkersifolia/PhigrosLibrary-Plugin/assets/117198625/0b0ab079-0e9b-4e64-a1f0-577161da8fc1)
或许可以试试这个？

**Comment by Walkersifolia** [comment]
> > 
> 
> node模块的puppeteer和lib里面的代码写法不太一样，我有空搭一个喵崽看一下吧，云崽插件无法完全兼容喵崽是很正常的

和我刚刚说的一样，node模块的puppeteer不支持我所需的功能，虽然都叫puppeteer

**Comment by S-t-e-v-e-e** [comment]
哦
