### ISSUE TITLE
感觉细节上可以添加更多

### ISSUE THREAD

**Issue by MoYoez** [Walkersifolia/PhigrosLibrary-plugin#7]
这个ChallengeMode的话 按照设计是Gold 45带对应颜色，不过既然模仿了游戏效果，可以试着向上偏移一点

分数acc可以偏移一下，渲染是偏右的()

绑定的话可以考虑下配合网页前端传入，或者考虑生成那种加密码(前后端算法一致，可无需考虑前端通信问题，可部署于vercel那种)

事实上是查分是可以向下查询的，可以考虑一下向下查询功能()

**Comment by Walkersifolia** [comment]
我真的感觉自己的脑子出现了什么问题（）
看到的时候还在想，游戏不就是那样的吗，然后上游戏看了一眼（草
现在目前在做喵崽的兼容，有点难办

**Comment by QiXingQXX** [comment]
> 这个ChallengeMode的话 按照设计是Gold 45带对应颜色，不过既然模仿了游戏效果，可以试着向上偏移一点
> 
> 分数acc可以偏移一下，渲染是偏右的()
> 
> 绑定的话可以考虑下配合网页前端传入，或者考虑生成那种加密码(前后端算法一致，可无需考虑前端通信问题，可部署于vercel那种)
> 
> 事实上是查分是可以向下查询的，可以考虑一下向下查询功能()

看看你的渲染图（）我这acc没偏

绑定的话没明白，是指再用单独的一套算法存储token？

**Comment by MoYoez** [comment]
> > 这个ChallengeMode的话 按照设计是Gold 45带对应颜色，不过既然模仿了游戏效果，可以试着向上偏移一点
> > 分数acc可以偏移一下，渲染是偏右的()
> > 绑定的话可以考虑下配合网页前端传入，或者考虑生成那种加密码(前后端算法一致，可无需考虑前端通信问题，可部署于vercel那种)
> > 事实上是查分是可以向下查询的，可以考虑一下向下查询功能()
> 
> 看看你的渲染图（）我这acc没偏
> 
> 绑定的话没明白，是指再用单独的一套算法存储token？

![{41678646-D72B-2851-A406-E518E353EFCB}](https://github.com/Walkersifolia/PhigrosLibrary-plugin/assets/30306672/630e6061-2014-408b-a216-07b3084afbf7)
这个是我自己的 其实咱倾向于最后一位分数和acc百分比对齐( 貌似也没特别齐（  ,如果是按照设计图来的话是倒数第二位分数和%对齐的，acc首位是在第二位半左右的位置，感觉这个可能要调小一点点acc的字体，应该差不多

绑定的话我是放在一个单独的网站上获取加密后的Session,https://pgr.impart.icu
我是专门用vue3+php的方案写了套破前端页面，通过加密后的数据再传入到大群里面，bot端解密后解析即可（
这样的目的主要是在bot不允许私聊的情况下绑定的快捷方式了，不需要本身自己还专门做一套什么 验证码+邮箱绑定等 奇怪的东西，不过唯一的缺点是需要在vercel或者netlify上专门部署个前端网页来接受信息并处理（

**Comment by MoYoez** [comment]
> 我真的感觉自己的脑子出现了什么问题（） 看到的时候还在想，游戏不就是那样的吗，然后上游戏看了一眼（草 现在目前在做喵崽的兼容，有点难办

没关系啦，咱做的第一版也被骂了各种地方不好看x
慢慢做就好了x 不急

**Comment by QiXingQXX** [comment]
> > > 这个ChallengeMode的话 按照设计是Gold 45带对应颜色，不过既然模仿了游戏效果，可以试着向上偏移一点
> > > 分数acc可以偏移一下，渲染是偏右的()
> > > 绑定的话可以考虑下配合网页前端传入，或者考虑生成那种加密码(前后端算法一致，可无需考虑前端通信问题，可部署于vercel那种)
> > > 事实上是查分是可以向下查询的，可以考虑一下向下查询功能()
> > 
> > 
> > 看看你的渲染图（）我这acc没偏
> > 绑定的话没明白，是指再用单独的一套算法存储token？
> 
> ![{41678646-D72B-2851-A406-E518E353EFCB}](https://user-images.githubusercontent.com/30306672/247466095-630e6061-2014-408b-a216-07b3084afbf7.PNG) 这个是我自己的 其实咱倾向于最后一位分数和acc百分比对齐( 貌似也没特别齐（ ,如果是按照设计图来的话是倒数第二位分数和%对齐的，acc首位是在第二位半左右的位置，感觉这个可能要调小一点点acc的字体，应该差不多
> 
> 绑定的话我是放在一个单独的网站上获取加密后的Session,https://pgr.impart.icu 我是专门用vue3+php的方案写了套破前端页面，通过加密后的数据再传入到大群里面，bot端解密后解析即可（ 这样的目的主要是在bot不允许私聊的情况下绑定的快捷方式了，不需要本身自己还专门做一套什么 验证码+邮箱绑定等 奇怪的东西，不过唯一的缺点是需要在vercel或者netlify上专门部署个前端网页来接受信息并处理（

对齐的话以我自己肯定是居中的（但没玩过游戏不清楚游戏内的）

我这里还是倾向于屏蔽群内绑定，加好友是自动同意的，已经和圈圈讲好了改一下限制


（会vue的都是佬，我只会手搓）

**Comment by MoYoez** [comment]
> > > > 这个ChallengeMode的话 按照设计是Gold 45带对应颜色，不过既然模仿了游戏效果，可以试着向上偏移一点
> > > > 分数acc可以偏移一下，渲染是偏右的()
> > > > 绑定的话可以考虑下配合网页前端传入，或者考虑生成那种加密码(前后端算法一致，可无需考虑前端通信问题，可部署于vercel那种)
> > > > 事实上是查分是可以向下查询的，可以考虑一下向下查询功能()
> > > 
> > > 
> > > 看看你的渲染图（）我这acc没偏
> > > 绑定的话没明白，是指再用单独的一套算法存储token？
> > 
> > 
> > ![{41678646-D72B-2851-A406-E518E353EFCB}](https://user-images.githubusercontent.com/30306672/247466095-630e6061-2014-408b-a216-07b3084afbf7.PNG) 这个是我自己的 其实咱倾向于最后一位分数和acc百分比对齐( 貌似也没特别齐（ ,如果是按照设计图来的话是倒数第二位分数和%对齐的，acc首位是在第二位半左右的位置，感觉这个可能要调小一点点acc的字体，应该差不多
> > 绑定的话我是放在一个单独的网站上获取加密后的Session,[pgr.impart.icu](https://pgr.impart.icu) 我是专门用vue3+php的方案写了套破前端页面，通过加密后的数据再传入到大群里面，bot端解密后解析即可（ 这样的目的主要是在bot不允许私聊的情况下绑定的快捷方式了，不需要本身自己还专门做一套什么 验证码+邮箱绑定等 奇怪的东西，不过唯一的缺点是需要在vercel或者netlify上专门部署个前端网页来接受信息并处理（
> 
> 对齐的话以我自己肯定是居中的（但没玩过游戏不清楚游戏内的）
> 
> 我这里还是倾向于屏蔽群内绑定，加好友是自动同意的，已经和圈圈讲好了改一下限制
> 
> （会vue的都是佬，我只会手搓）

设计的话咱感觉怎么美观怎么来就好了（ 也不一定要按照东城家设计百分百复刻(

加好友的话或许也可以(? 不过就咱目前碰到的问题是，如果你bot做的可能好一点的话 对方可以直接把你拉到他的群来用(qq对小群好友的邀请群申请是直接通过的，不需要同意)，如果号主不管理的话，过个几点天多了什么 不少发电人群在你bot发电 | 99+群信息爆炸 | bot莫名其妙封了(? ,风控加大，咱感觉是管理很麻烦的

不过应该也有更好的处理方式吧，可以学学其他家例如tomato那种，不过也更麻烦了x
