### ISSUE TITLE
为什么我端口放开了也启动了但就是连不上

### ISSUE THREAD

**Issue by S-t-e-v-e-e** [Walkersifolia/PhigrosLibrary-plugin#9]
![image](https://github.com/Walkersifolia/PhigrosLibrary-plugin/assets/117198625/09797471-b499-496c-92b0-ed482f378fdf)

**Comment by Walkersifolia** [comment]
你看我readme最前面三行大字写的是什么

**Comment by S-t-e-v-e-e** [comment]
我是傻逼

**Comment by S-t-e-v-e-e** [comment]
我搭个云崽看看

**Comment by Walkersifolia** [comment]
（（

**Comment by S-t-e-v-e-e** [comment]
![image](https://github.com/Walkersifolia/PhigrosLibrary-plugin/assets/117198625/12a8e561-2e38-434b-af88-45e5c8946315)
好耶

**Comment by S-t-e-v-e-e** [comment]
几乎一模一样的报错（

**Comment by SakuraTairitsu** [comment]
> 你看我自述最前面三行大字写的是什么

在用喵崽修改版（自改，我用的旧puppeteer（也不是很久，四五月那版），可以兼容喵崽云崽东西和插件。喵佬重写了puppeteer差不多把方法给删完了，所以插件调用时报错。可以使用以前还没改过的，除了控制台在首次启动时会有个[WARN]提示，没有别的问题（似乎之前有人说这版puppeteer用不了？我是从来没有出现过，使用完全正常ovo
![image](https://github.com/Walkersifolia/PhigrosLibrary-plugin/assets/135034632/183e1f52-cd4d-4734-9542-c8979354d5bf)
![$7RR8SMOW%JK)AQ~(EYGWK7](https://github.com/Walkersifolia/PhigrosLibrary-plugin/assets/135034632/18c8b42a-fa57-4d54-bb62-c004eeddcdd1)

**Comment by Walkersifolia** [comment]
> > 你看我自述最前面三行大字写的是什么
> 
> 在用喵崽修改版（自改，我用的旧puppeteer（也不是很久，四五月那版），可以兼容喵崽云崽东西和插件。喵佬重写了puppeteer差不多把方法给删完了，所以插件调用时报错。可以使用以前还没改过的，除了控制台在首次启动时会有个[WARN]提示，没有别的问题（似乎之前有人说这版puppeteer用不了？我是从来没有出现过，使用完全正常ovo ![image](https://user-images.githubusercontent.com/135034632/248511025-183e1f52-cd4d-4734-9542-c8979354d5bf.png) ![$7RR8SMOW%JK)AQ~(EYGWK7](https://user-images.githubusercontent.com/135034632/248511077-18c8b42a-fa57-4d54-bb62-c004eeddcdd1.png)

前面有个issue有个人截图的，我自己是不常用喵崽的，最新版喵崽lib下面的puppeteer.js点开啥都没有，我考虑一下插件内置puppeteer吧，没办法
